
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int id = 9;
  public static final int coma = 4;
  public static final int claves = 12;
  public static final int registros = 13;
  public static final int cadena = 11;
  public static final int apar = 2;
  public static final int EOF = 0;
  public static final int menos = 6;
  public static final int numero = 10;
  public static final int error = 1;
  public static final int por = 7;
  public static final int cpar = 3;
  public static final int mas = 5;
  public static final int dividir = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "apar",
  "cpar",
  "coma",
  "mas",
  "menos",
  "por",
  "dividir",
  "id",
  "numero",
  "cadena",
  "claves",
  "registros"
  };
}

