
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresArchivoDatos;

import java.util.*;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class analisis_sintactico_2 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public analisis_sintactico_2() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public analisis_sintactico_2(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public analisis_sintactico_2(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\004\000\002\003\003\000\002\007" +
    "\014\000\002\010\005\000\002\010\003\000\002\011\003" +
    "\000\002\011\003\000\002\012\006\000\002\012\005\000" +
    "\002\013\005\000\002\013\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\034\000\004\020\005\001\002\000\004\002\000\001" +
    "\002\000\004\014\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\004\012\011\001\002\000" +
    "\006\016\012\017\013\001\002\000\010\006\ufffb\011\ufffb" +
    "\013\ufffb\001\002\000\010\006\ufffc\011\ufffc\013\ufffc\001" +
    "\002\000\006\006\016\013\017\001\002\000\006\006\ufffd" +
    "\013\ufffd\001\002\000\006\016\012\017\013\001\002\000" +
    "\004\021\020\001\002\000\004\014\021\001\002\000\004" +
    "\012\022\001\002\000\004\010\024\001\002\000\006\010" +
    "\032\013\033\001\002\000\006\016\012\017\013\001\002" +
    "\000\006\006\030\011\027\001\002\000\006\006\ufff7\011" +
    "\ufff7\001\002\000\006\010\ufff9\013\ufff9\001\002\000\006" +
    "\016\012\017\013\001\002\000\006\006\ufff8\011\ufff8\001" +
    "\002\000\006\016\012\017\013\001\002\000\004\002\uffff" +
    "\001\002\000\006\006\030\011\035\001\002\000\006\010" +
    "\ufffa\013\ufffa\001\002\000\006\006\ufffe\013\ufffe\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\034\000\006\003\005\007\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\010\013\011\014\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\011\035\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\012\022\001\001" +
    "\000\002\001\001\000\006\011\025\013\024\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\030\001\001\000\002\001\001\000\006\011\025\013" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$analisis_sintactico_2$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$analisis_sintactico_2$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$analisis_sintactico_2$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  
    /*public static LinkedList<AcepErr> TablaErr=new LinkedList<AcepErr>();*/

    public String resultado = "";
    //Metodo al que se llama automaticamente ante algun error sintactico
    public void syntax_error(Symbol s)
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        System.out.println("!!!!!!! Error Sintactico Recuperado !!!!!!!");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado"));
        /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado");
            TablaErr.add(datos);
            */
    }

    //Metodo al que se llama en el momento en que ya no es posible una recuperacion de errores
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
    {        
        String lexema = s.value.toString();
        int fila = s.right;
        int columna = s.left;
        
        System.out.println("!!!!!!! Error Sintactico, Panic Mode !!!!!!! ");
        System.out.println("\t\tLexema: "+lexema);
        System.out.println("\t\tFila: "+fila);
        System.out.println("\t\tColumna: "+columna);

       /*AcepErr datos =new AcepErr(lexema, "ERROR SINTACTICO" ,fila,columna,"Simbolo no esperado Error Fatal");
                   TablaErr.add(datos);
                  */
        //lista_errores.add(new ErrorT(lexema, fila, columna,"sintactico" ,"Simbolo no esperado, Panic Mode"));
    }

    public void semantic(Symbol cur_token, String n) 
    {
        System.out.println("error semantico ");
    }

    public void semantic(String msg, Object obj) {}



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$analisis_sintactico_2$actions {


//METODOS Y VARIABLES QUE SOLO PUEDEN SER ACCEDIDAS DENTRO DEL PARSER
int exponente(int exp){
    int resultado= 1;
    for(int i=1; i<exp; i++){
        resultado = resultado *2;
    }
    return resultado;
}


  private final analisis_sintactico_2 parser;

  /** Constructor */
  CUP$analisis_sintactico_2$actions(analisis_sintactico_2 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$analisis_sintactico_2$do_action_part00000000(
    int                        CUP$analisis_sintactico_2$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintactico_2$parser,
    java.util.Stack            CUP$analisis_sintactico_2$stack,
    int                        CUP$analisis_sintactico_2$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$analisis_sintactico_2$result;

      /* select the action based on the action number */
      switch (CUP$analisis_sintactico_2$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-1)).value;
		RESULT = start_val;
              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-1)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$analisis_sintactico_2$parser.done_parsing();
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= CLAVEREGISTRO 
            {
              String RESULT =null;
		int lsleft = ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()).left;
		int lsright = ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()).right;
		String ls = (String)((java_cup.runtime.Symbol) CUP$analisis_sintactico_2$stack.peek()).value;
		
            
        
              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("INICIO",1, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // CLAVEREGISTRO ::= claves igual acorch LISTACLAVES ccorch registros igual acorch LISTAREGISTROS ccorch 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("CLAVEREGISTRO",5, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-9)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LISTACLAVES ::= LISTACLAVES coma CLAVE 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("LISTACLAVES",6, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTACLAVES ::= CLAVE 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("LISTACLAVES",6, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // CLAVE ::= cadena 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("CLAVE",7, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // CLAVE ::= numero 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("CLAVE",7, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // LISTAREGISTROS ::= LISTAREGISTROS allave LISTAVAL cllave 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("LISTAREGISTROS",8, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-3)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // LISTAREGISTROS ::= allave LISTAVAL cllave 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("LISTAREGISTROS",8, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // LISTAVAL ::= LISTAVAL coma CLAVE 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("LISTAVAL",9, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.elementAt(CUP$analisis_sintactico_2$top-2)), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // LISTAVAL ::= CLAVE 
            {
              String RESULT =null;

              CUP$analisis_sintactico_2$result = parser.getSymbolFactory().newSymbol("LISTAVAL",9, ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), ((java_cup.runtime.Symbol)CUP$analisis_sintactico_2$stack.peek()), RESULT);
            }
          return CUP$analisis_sintactico_2$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$analisis_sintactico_2$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$analisis_sintactico_2$do_action(
    int                        CUP$analisis_sintactico_2$act_num,
    java_cup.runtime.lr_parser CUP$analisis_sintactico_2$parser,
    java.util.Stack            CUP$analisis_sintactico_2$stack,
    int                        CUP$analisis_sintactico_2$top)
    throws java.lang.Exception
    {
              return CUP$analisis_sintactico_2$do_action_part00000000(
                               CUP$analisis_sintactico_2$act_num,
                               CUP$analisis_sintactico_2$parser,
                               CUP$analisis_sintactico_2$stack,
                               CUP$analisis_sintactico_2$top);
    }
}

}
